### ISSUE TITLE
Conference Call to discuss MVVM

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/dotnet-dss-examples#6]
Lets have a quick conference call to discuss MVVM and what we could do to add to this project

**Comment by ktarbet** [comment]
Here is a suggested topic:

We have a DSSFile (database) that reads and writes TimeSeries.  The TimeSeries is edited/displayed in a View.    How can these objects (database,TimeSeries,View) work well together?

**Comment by HenryGeorgist** [comment]
Interfaces!

In general I create separate dlls for my model objects, modelviewobjects, and my view objects.

My view references my modelview dll, my modelview references my viewmodel dll.

I also tend to have a single library of interfaces, data structures that are common across all libraries, a timeseries interface might be something that is necessary to be in that abstraction layer. 

it seems like you need a timeseries interface which can be implemented in any library that needs to communicate  times and values (and any other important data elements).
